"""Shared app defaults for Tally Hub modules."""

TALLY_HUB_APP_TITLE = "Tally Hub v2.0"
SALES_CONVERTER_APP_TITLE = "Monthly Client Tally Converter"

TALLY_HUB_STATE_FILE = "tally_hub_v2_state.json"
SALES_CONVERTER_STATE_FILE = "monthly_client_tally_state.json"

DEFAULT_COMPANY_PROFILE_NAME = "HR FEEDS & FOODS"
DEFAULT_SALES_LEDGER = "LOCAL SALES"
DEFAULT_PURCHASE_LEDGER = "INTERSTATE PURCHASE"
DEFAULT_PURCHASE_LOCAL_LEDGER = "LOCAL PURCHASE"
DEFAULT_SALES_PARTY_PARENT = "Sundry Debtors"
DEFAULT_PURCHASE_PARTY_PARENT = "Sundry Creditors"
DEFAULT_STOCK_PARENT = "Primary"
DEFAULT_GODOWN = "Main Location"
DEFAULT_BATCH = "Primary Batch"
DEFAULT_FALLBACK_UNIT = "Bag"
